name: Deploy Pomodoro App

on:
  push:
    branches:
      - main # Veya repondaki ana branch adı 'master' ise 'master' yapabilirsin

permissions:
  contents: read
  pages: write
  id-token: write

concurrency:
  group: "pages"
  cancel-in-progress: true

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Repoyu Klonla
        uses: actions/checkout@v4

      - name: Node.js Kurulumu
        uses: actions/setup-node@v4
        with:
          node-version: 20
          cache: "npm"

      - name: Bağımlılıkları Yükle
        run: npm ci

      - name: Vite ile Build Al
        run: npm run build

      - name: GitHub Pages Yapılandırması
        uses: actions/configure-pages@v5

      - name: Artifact Oluştur (dist)
        uses: actions/upload-pages-artifact@v3
        with:
          path: "./dist"

      - name: GitHub Pages'e Yayınla
        id: deployment
        uses: actions/deploy-pages@v4
